image: registry.nic.cz/turris/turrishw/python3.7
before_script:
    - pip install tox

stages:
  - test

python3:
  stage: test
  script:
    - tox -e py37

lint:
  stage: test
  script:
    - tox -e lint
